### ISSUE TITLE
Composite Skycon in a component yields an unexpected error: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)

### ISSUE THREAD

**Issue by mikuya707** [roadmanfong/react-skycons#6]
My code below caused the error 

> React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)

```
    const React = require('react')
    var Skycons = require('react-skycons');

    var WeatherCard = React.createClass({

      render: function() {
        console.log('props are', this.props)
        var iconName = this.props.icon.toUpperCase();
        console.log('iconname is', iconName);
        var icon = <Skycons color='black' icon={iconName} autoplay={true}  />
        return (
          <div className="card">
              <p>{this.props.date}</p>
              <p>{this.props.description}</p>
              {icon}
              <div>
                <span>{this.props.temp.max}</span>
                 <span>{this.props.temp.max}</span>
              </div>

          </div>

        );
      }
    });

    module.exports = WeatherCard;
```

I am suspecting it's coming from Skycons component? Please advise. Thanks

**Comment by roadmanfong** [comment]
you end with `</div>` but you don't have start `<div>` .  
Please provide full example.
also you can use 
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
to highlight your code.

**Comment by mikuya707** [comment]
Hi, sorry about the bad formatting, the code example is edited.

**Comment by mikuya707** [comment]
The problem is solved now. I used  `var Skycons = require('react-skycons').default;` and it eliminated the error.

However, the new issue is that when the icons are rendered, it's not showing in the dom. I inspected it in the console, the canvas element exists, yet it's not showing or rendered properly. I see three warnings:

> Warning: You are manually calling a React.PropTypes validation function for the `color` prop on `ReactSkycons`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning 
> @ Warning: You are manually calling a React.PropTypes validation function for the `autoplay` prop on `ReactSkycons`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning
>  @ Warning: You are manually calling a React.PropTypes validation function for the `icon` prop on `ReactSkycons`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

code example:

```
     const React = require('react')
     var Skycons = require('react-skycons').default;
    var WeatherCard = React.createClass({

    render: function() {
      console.log('props are', this.props)
      var iconName = this.props.icon.toUpperCase().replace(/[-]/g, '_');
      console.log('iconname is', iconName);
      var icon = <Skycons color='black' icon={iconName} autoplay={true}  />
      return (
        <div className="card">
            <p>{this.props.date}</p>
            <p>{this.props.description}</p>
            <div>
              {icon}
            </div>
            <div>
              <span>{this.props.temp.max}</span>
               <span>{this.props.temp.max}</span>
            </div>

        </div>

      );
    }
    });

    module.exports = WeatherCard;
```

**Comment by jforaker** [comment]
Any update on this @roadmanfong ? I'm experiencing the same issue as well.

**Comment by jforaker** [comment]
@mikuya707 after some fussing around, I got it to render by doing this:

``` javascript
import Skycons from 'react-skycons';

var Demo = React.createClass({
  render: function () {
    return (
      <Skycons color="black" icon="PARTLY_CLOUDY_DAY"/>
    );
  }
});

//and then...


render(
  <div>
    <Demo />
  </div>,
  document.getElementById('app')
);
```

**Comment by jonathan-dejong** [comment]
Here's what worked for me with a new create-react-app build.

At the top before the class
`import Skycons from 'react-skycons';`

Then I set a default icon in constructor with 
```
this.state = {
			temp: 0,
			weather: '?',
			icon: 'CLEAR_DAY',
			city: 'Lund'
		};
```

Then I set the icon in a promise from darksky.net

```
t.setState({
					icon: results.currently.icon.replace('-', '_').toUpperCase(),
					weather: results.currently.summary,
					temp: Math.round( results.currently.temperature ),
				});
```

and finally I can just output the skycon component directly in my render. I include the whole render just for clarity:

```
<div className="weather">
				<span className="weather-left">
					<Skycons color="white" icon={this.state.icon} autoplay={true}/>
				</span>
				<span className="weather-right">
					<span className="weather-temp">{this.state.temp}°C</span>
					<span className="weather-description">{this.state.weather}</span>
					<span className="weather-city">{this.state.city}</span>
				</span>
			</div>
```


Thank you guys for getting me there with your answers!
